[package]
name = "with-mio-serial"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dfr0299 = { path = "../../dfr0299", features = ["std"] }

color-eyre = "0.6"
mio-serial = "5"
