[package]
name = "dfr0299"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[features]
std = ["num_enum/std"]

[dependencies]
num_enum = { version = "0.5", default_features = false }


[dev-dependencies]
pretty_assertions = "1"
